# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nick Frost
email: nickfrostatx@gmail.com
description: >
  Nick Frost is a programmer and CS student at Cal Poly SLO.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.nfrost.me" # the base hostname & protocol for your site
github_username:  nickfrostatx

# Build settings
markdown: kramdown
